Repository jalantechnologies/github-ci, pull requests merged in 2023-08, with the labels that each got.

#19 (bug) remove dependency from 'ci_version' input
  .github/workflows/ci.yml
Labels: bug

#26 (bug) Caching does not works in monorepo setup
  .github/actions/build/action.yml
  .github/workflows/ci.yml
Labels: bug

#29 (bug) remove dependency from 'ci_version' input from clean workflow
  .github/workflows/ci.yml
  .github/workflows/clean.yml
Labels: bug

#30 (chore) update documentation on development and release process
  README.md
Labels: documentation

#31 Release v1.2
  CHANGELOG
  README.md
Labels: release

#32 (fix) Fix issue with workflow version
  .github/workflows/ci.yml
  .github/workflows/clean.yml
Labels: bug

#34 (bug) doppler kube secret is not updated when token is changed
  lib/kube/clean.sh
  lib/kube/deploy.sh
Labels: bug

#37 (bug) Deployment fails if the branch name does not passes the label validation
  lib/kube/deploy.sh
Labels: bug

#38 (feat) Add support for tagging kubernetes resources with workflow attempt info
  .github/workflows/ci.yml
Labels: enhancement, deployment, kubernetes

#41 (bug) Clean up workflow is not working as expected
  .github/workflows/clean.yml
Labels: bug

#43 (feat) Build on PRs should be able to use cache from base branch
  .github/actions/build/action.yml
Labels: enhancement
